//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shp2Sql.Sandbox
{
	using System;
	using System.CodeDom.Compiler;
	using System.ComponentModel;
	using System.Diagnostics;
	using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


	/// <remarks/>
	[GeneratedCode("xsd", "4.6.1055.0")]
	[Serializable()]
	[DebuggerStepThrough()]
	[DesignerCategory("code")]
	[XmlType(AnonymousType=true)]
	[XmlRoot(Namespace="", IsNullable=false)]
	public partial class citeinfo : object, INotifyPropertyChanged {
    
		private string originField;
    
		private string pubdateField;
    
		private string titleField;
    
		private string editionField;
    
		private string geoformField;
    
		private string onlinkField;
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
		public string origin {
			get {
				return this.originField;
			}
			set {
				this.originField = value;
				this.RaisePropertyChanged("origin");
			}
		}
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
		public string pubdate {
			get {
				return this.pubdateField;
			}
			set {
				this.pubdateField = value;
				this.RaisePropertyChanged("pubdate");
			}
		}
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
		public string title {
			get {
				return this.titleField;
			}
			set {
				this.titleField = value;
				this.RaisePropertyChanged("title");
			}
		}
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
		public string edition {
			get {
				return this.editionField;
			}
			set {
				this.editionField = value;
				this.RaisePropertyChanged("edition");
			}
		}
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
		public string geoform {
			get {
				return this.geoformField;
			}
			set {
				this.geoformField = value;
				this.RaisePropertyChanged("geoform");
			}
		}
    
		/// <remarks/>
		[XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
		public string onlink {
			get {
				return this.onlinkField;
			}
			set {
				this.onlinkField = value;
				this.RaisePropertyChanged("onlink");
			}
		}
    
		public event PropertyChangedEventHandler PropertyChanged;
    
		protected void RaisePropertyChanged(string propertyName) {
			PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null)) {
				propertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}